export const meta = {
  name: 'rest-modernize',
  description: '남은 전 과목(경영·경제·민법·회계감사·행정소송·미분류 등) 기출을 현행화 + 내 해설. Opus.',
  phases: [{ title: '현행화', detail: '파일별 에이전트가 과목 자동판별해 현행화' }],
}
const SCHEMA = { type:'object', additionalProperties:false,
  required:['file','total','current','amended','obsolete','verify','out_path'],
  properties:{ file:{type:'string'}, total:{type:'number'}, current:{type:'number'}, amended:{type:'number'}, obsolete:{type:'number'}, verify:{type:'number'}, obsolete_nos:{type:'array',items:{type:'string'}}, out_path:{type:'string'}, notes:{type:'string'} } }
const PROMPT = "당신은 대한민국 전문자격시험(회계사·세무사·법무사) 출제분야 전문가입니다. 이 기출 카드의 과목을 stem과 파일명으로 파악하고, 그 분야의 현행 기준(2026년 1월)에 맞게 현행화하세요.\n\n과목별 기준:\n- 법학(민법·형법·민사소송·민사집행·부동산등기·상업등기·비송사건절차·공탁·가족관계등록·헌법·행정소송법): 현행 조문·판례 기준. 개정·폐지 조항 점검.\n- 회계감사: 현행 회계감사기준(K-ISA).\n- 경영학·경제원론·재정학: 학문 이론이라 대부분 '현행유지'(개정 개념 없음). 다만 제도·법규(예 공정거래·조세) 인용 문항만 변동 점검.\n- 영어 등 비법규 과목: 현행유지.\n- 한 파일에 여러 과목이 섞여 있으면(미분류 1차 통합문제 등) 각 문제의 실제 주제에 맞게 판단.\n\n1) Read 도구로 읽기: <<PATH>>  (구조 { meta, questions:[{no,stem,choices:[{no,text}],answer,explanation}] }. PDF추출 공백누락 가능—의미 복원.)\n2) 각 문제: 정답 검증 + 당신 언어 해설(핵심 조문/이론, 한국어). law_status: 현행유지 / 개정-개선(stem·choices·answer 수정+change_note) / 구법-삭제(obsolete_nos). 확신없으면 현행유지+verify=true.\n3) Write 도구로 저장: C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_updated\\updated__<원본파일명>\n   { meta:(원본+{updated_by:'workflow-기타',cutoff:'2026-01'}), questions:[{no,topic,stem,choices,answer,my_explanation,law_status,verify,change_note?}], obsolete_nos:[...] } (UTF-8 한글)\n4) StructuredOutput 반환: file,total,current,amended,obsolete,verify,obsolete_nos,out_path,notes."
function prompt(path){ return PROMPT.replace(/<<PATH>>/g, path) }
const EMBEDDED = [
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\bupmu__2014년 제20회 법무사 상등법 기출문제__2014 제20회 법무사 상등법 기출문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2000년도 제1차시험 문제 및 정답__2000년-경영학(1형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2000년도 제1차시험 문제 및 정답__2000년-경제원론(1형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2000년도 제1차시험 문제 및 정답__2000년-영어1(1형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2005년도 제1차시험 문제 및 정답__2005년_경영학1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2005년도 제1차시험 문제 및 정답__2005년_경제원론1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2005년도 제1차시험 문제 및 정답__2005년_영어1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2006년도 제1차시험 문제 및 확정정답__2006년_경영학1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2006년도 제1차시험 문제 및 확정정답__2006년_경제원론1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2006년도 제1차시험 문제 및 확정정답__2006년_영어1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2006년도 제2차시험 문제__2006년도_회계감사(최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2007년도 제1차시험 문제 및 확정정답__2007년+경영학+제1형(최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2007년도 제1차시험 문제 및 확정정답__2007년+경제학+제1형(최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2008년도 제1차시험 문제 및 확정정답__2008년+경영학+제1형(최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2008년도 제1차시험 문제 및 확정정답__2008년+경제원론+제1형(확정).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2009년도 제1차시험 문제 및 확정정답__경영학(1형_최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2009년도 제1차시험 문제 및 확정정답__경제원론-1형-최종.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2010년도 제1차시험 문제 및 확정정답__경영학(1형)_최종.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2010년도 제1차시험 문제 및 확정정답__경제원론(1형)_최종.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2011년도 제1차시험 문제 및 확정정답__★경영학_1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2011년도 제1차시험 문제 및 확정정답__★경제원론_1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2011년도 제2차 시험문제__2011년+2차++회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2012년도 제47회 공인회계사 제1차시험 문제 및 확정정답__☆경영학_1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2012년도 제47회 공인회계사 제1차시험 문제 및 확정정답__☆경제원론_1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2013년도 제48회 공인회계사 제1차시험 문제 및 확정정답__1-1+경영학(1형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2013년도 제48회 공인회계사 제1차시험 문제 및 확정정답__1-2+경제원론(1형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2014년도 공인회계사 제2차 시험문제__(1-3)회계감사문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2014년도 제49회 공인회계사 제1차시험 문제 및 확정정답__경영학-1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2014년도 제49회 공인회계사 제1차시험 문제 및 확정정답__경제원론-1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2015년도 제50회 공인회계사 제1차시험 문제 및 확정정답__2015년-01-1.경영학+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2015년도 제50회 공인회계사 제1차시험 문제 및 확정정답__2015년-01-2.경제원론+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2015년도 제50회 공인회계사 제2차 시험문제__2015_(1-3)회계감사+문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2016년도 제51회 공인회계사 제1차시험 문제 및 확정정답__01-1.경영학+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2016년도 제51회 공인회계사 제1차시험 문제 및 확정정답__01-2.경제원론+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2016년도 제51회 공인회계사 제2차 시험문제__(1-2)재무관리+문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2016년도 제51회 공인회계사 제2차 시험문제__(1-3)회계감사+문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2017년도 제52회 공인회계사 제1차시험 문제 및 확정정답__01-1.+경영학+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2017년도 제52회 공인회계사 제1차시험 문제 및 확정정답__01-2.+경제원론+1형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2017년도 제52회 공인회계사 제2차시험 문제__1-2.+재무관리.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2017년도 제52회 공인회계사 제2차시험 문제__1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2018년도 제53회 공인회계사 제1차시험 문제 및 확정정답__(1교시)+경영학+·+경제원론(1형)_문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2018년도 제53회 공인회계사 제2시험 문제__(2018)+1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2019년도 제54회 공인회계사 제1차시험 문제 및 확정답안__01.+경영학_경제원론(1형)_문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2019년도 제54회 공인회계사 제2차시험 문제__(2019)1-2.+재무관리.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2019년도 제54회 공인회계사 제2차시험 문제__(2019)1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2020년도 제55회 공인회계사 제1차시험 문제 및 가답안__01.+경영학+경제원론(1형)_문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2020년도 제55회 공인회계사 제2차시험 문제__(2020)1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2020학년도 제55회 공인회계사 제1차시험 문제 및 확정답안__01.+경영학+경제원론(1형)_문제(최종)_2020.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2021년도 제56회 공인회계사 제1차시험 문제 및 확정답안__01.+경영학+경제원론(1형)_문제(최종).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2021년도 제56회 공인회계사 제2차시험 문제__(2021)1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2022년도 제57회 공인회계사 제1차시험 문제 및 확정답안__01.+경영학+경제원론(1형)_문제_2022.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2022년도 제57회 공인회계사 제2차시험 문제__(2022)1-3.+회계감사.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2023년도 제58회 공인회계사 제1차시험 문제 및 가답안__01.+경영학+경제원론(1형)_문제_2023.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2023년도 제58회 공인회계사 제2차시험 문제(PDF 버전)__1-3+회계감사+문제(2023-2).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2024년도 제59회 공인회계사 제2차시험 문제__1-3+회계감사+문제(2024-2).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\cpa__2025년도 제60회 공인회계사 제2차시험 문제__1-3+회계감사+문제(2025-2).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\semu__2017년 세무사 1차 1교시 A형 문제지입니다__1교시 A형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\semu__2017년 세무사 1차 1교시 B형 문제지입니다__1교시 B형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\semu__2017년 세무사 1차 2교시_A형_민법(선택) 문제지입니다__2교시_A형_민법.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\semu__2017년 세무사 1차 2교시_B형_민법(선택) 문제지입니다__2교시_B형_민법.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__101222_22년 법무사 2차 기출해설 자료_1.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__105238_2023년 제29회 법무사 1차 민법_부등법_민집법_공탁법 해설_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__110646_[김중연 교수]2024년 제30회 법무사1차 시험 민법 해설_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__111496_[김현기 법무사]2024년 제30회 법무사2차 형법 총평 및 해설 자료_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__111500_[송시영 변호사]2024년 30회 법무사2차 시험 형소법 총평 및 해설_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__27213_제16회 법무사 민사집행법 해설(김지후)_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__27214_제16회 법무사 가족관계등록법 해설(김지후)_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__32854_제 17회 법무사 1차 가족관계등록법 해설 및 총평_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__47070_제19회 법무사 1차 헌법 기출문제_해설_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__48021_제19회 법무사 1차 상업등기및비송사건절차법 기출문제_해설(1책형) - 문승진_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\web_bupmu__95660_21년 법무사 1차 기출해설 자료_0.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_bupmu__2007년 제13회 법무사 제1차 시험문제 (1책형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_bupmu__제13회 법무사  제2차 시험 문제.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_bupmu__제14회 법무사1차 1책형1,2교시.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_bupmu__제15회_법무사_제1차시험_문제(1책형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_bupmu__제15회_법무사_제2차시험_문제(2책형).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 1교시 A형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 1교시 B형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 2교시 A형(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 2교시 A형(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 2교시 B형(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2021년도 제58회 세무사 1차 시험 2교시 B형(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2022년도 제59회 세무사 1차 시험 1교시 문제지 A형.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2022년도 제59회 세무사 1차 시험 2교시 문제지 A형(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2022년도 제59회 세무사 1차 시험 2교시 문제지 A형(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2023년 제60회 세무사 1차시험 1교시 문제지.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2023년 제60회 세무사 1차시험 2교시 문제지(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2023년 제60회 세무사 1차시험 2교시 문제지(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2024년도 제61회 세무사 1차시험 1교시 시험지 원본.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2024년도 제61회 세무사 1차시험 2교시 시험지 원본(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2024년도 제61회 세무사 1차시험 2교시 시험지 원본(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2025년도 제62회 세무사 1차시험 1교시 시험지 원본.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2025년도 제62회 세무사 1차시험 2교시 시험지 원본(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2025년도 제62회 세무사 1차시험 2교시 시험지 원본(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2026년도 제63회 세무사 1차시험 1교시 시험지 원본.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2026년도 제63회 세무사 1차시험 2교시 시험지 원본(민법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_semu__2026년도 제63회 세무사 1차시험 2교시 시험지 원본(행정소송법).json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_zip__1교시 경영학 경제원론(1형)_문제_2025.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_zip__2교시.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_zip___01.경영학(1형)문제_2024.json",
  "C:\\todo_manual_dashboard\\law_dashboard_work\\data\\exams_cards\\zip_zip___01.경제원론(1형)문제_2024.json"
]
phase('현행화')
const items = (Array.isArray(args) && args.length) ? args : EMBEDDED
log('남은과목 처리 대상: ' + items.length + '파일')
const results = await pipeline(items, (path) => {
  const base = (path.match(/[^\/]+$/) || [path])[0]
  return agent(prompt(path), { label:'기타:'+base.slice(0,36), phase:'현행화', schema:SCHEMA, agentType:'general-purpose', model:'opus' })
})
const ok=results.filter(Boolean)
const s=(k)=>ok.reduce((a,r)=>a+(r[k]||0),0)
const summary={files_done:ok.length, files_failed:results.length-ok.length, total_q:s('total'), current:s('current'), amended:s('amended'), obsolete:s('obsolete'), verify:s('verify'), obsolete_detail:ok.filter(r=>(r.obsolete||0)>0).map(r=>({file:r.file,nos:r.obsolete_nos}))}
log('남은과목 현행화: '+JSON.stringify({files:summary.files_done,q:summary.total_q,amended:summary.amended,obsolete:summary.obsolete,verify:summary.verify}))
return summary
